// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: runtime.proto

package runtime

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeService_ExchangeRuntimeToken_FullMethodName    = "/runtime.v1.RuntimeService/ExchangeRuntimeToken"
	RuntimeService_ResolveRegistration_FullMethodName     = "/runtime.v1.RuntimeService/ResolveRegistration"
	RuntimeService_ConfirmRegistration_FullMethodName     = "/runtime.v1.RuntimeService/ConfirmRegistration"
	RuntimeService_CreateOrder_FullMethodName             = "/runtime.v1.RuntimeService/CreateOrder"
	RuntimeService_VerifyAndConfirmPayment_FullMethodName = "/runtime.v1.RuntimeService/VerifyAndConfirmPayment"
	RuntimeService_GetOrder_FullMethodName                = "/runtime.v1.RuntimeService/GetOrder"
	RuntimeService_SyncIdentity_FullMethodName            = "/runtime.v1.RuntimeService/SyncIdentity"
	RuntimeService_SyncVerificationStatus_FullMethodName  = "/runtime.v1.RuntimeService/SyncVerificationStatus"
	RuntimeService_DisableIdentity_FullMethodName         = "/runtime.v1.RuntimeService/DisableIdentity"
	RuntimeService_GetBalance_FullMethodName              = "/runtime.v1.RuntimeService/GetBalance"
	RuntimeService_ListLedger_FullMethodName              = "/runtime.v1.RuntimeService/ListLedger"
	RuntimeService_GetSkuCatalog_FullMethodName           = "/runtime.v1.RuntimeService/GetSkuCatalog"
	RuntimeService_GetOfferCatalog_FullMethodName         = "/runtime.v1.RuntimeService/GetOfferCatalog"
	RuntimeService_ListSiteBranding_FullMethodName        = "/runtime.v1.RuntimeService/ListSiteBranding"
)

// RuntimeServiceClient is the client API for RuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RuntimeService 是工作台可调用的运行时订单与支付控制面白名单。
type RuntimeServiceClient interface {
	// ExchangeRuntimeToken 用 mTLS 客户端证书换取短期不透明访问令牌。
	ExchangeRuntimeToken(ctx context.Context, in *ExchangeRuntimeTokenRequest, opts ...grpc.CallOption) (*ExchangeRuntimeTokenReply, error)
	// ResolveRegistration 解析公有 site token 或 dedicated scope，产出十分钟 intent。
	ResolveRegistration(ctx context.Context, in *ResolveRegistrationRequest, opts ...grpc.CallOption) (*RegistrationIntent, error)
	// ConfirmRegistration 单事务创建身份、成员关系、归属、邀请码占用与可选赠送。
	ConfirmRegistration(ctx context.Context, in *ConfirmRegistrationRequest, opts ...grpc.CallOption) (*RegistrationReply, error)
	// CreateOrder 从目录价格行冻结应付金额与当前付款方。
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error)
	// VerifyAndConfirmPayment 复验渠道原始证明并原子提交单次 grant 或周期计划。
	VerifyAndConfirmPayment(ctx context.Context, in *VerifyAndConfirmPaymentRequest, opts ...grpc.CallOption) (*VerifyAndConfirmPaymentReply, error)
	// GetOrder 返回当前 actor 付款方范围内的订单稳定事实。
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderReply, error)
	// SyncIdentity 把已存在 identity 的最新生命周期事实同步为 active。
	SyncIdentity(ctx context.Context, in *SyncIdentityRequest, opts ...grpc.CallOption) (*IdentityReply, error)
	// SyncVerificationStatus 只同步实名状态、时点与不可逆凭证引用。
	SyncVerificationStatus(ctx context.Context, in *SyncVerificationStatusRequest, opts ...grpc.CallOption) (*IdentityReply, error)
	// DisableIdentity 把已存在 identity 的最新生命周期事实同步为 disabled。
	DisableIdentity(ctx context.Context, in *DisableIdentityRequest, opts ...grpc.CallOption) (*IdentityReply, error)
	// GetBalance 按 lot 聚合派生账户账面余额与免费 / 付费拆分。
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*BalanceReply, error)
	// ListLedger 按稳定全序返回用户可见额度流水。
	ListLedger(ctx context.Context, in *ListLedgerRequest, opts ...grpc.CallOption) (*LedgerReply, error)
	// GetSkuCatalog 返回当前生效的公开 SKU 售价目录。
	GetSkuCatalog(ctx context.Context, in *GetSkuCatalogRequest, opts ...grpc.CallOption) (*SkuCatalogReply, error)
	// GetOfferCatalog 返回当前生效的公开 Offer 售价目录。
	GetOfferCatalog(ctx context.Context, in *GetOfferCatalogRequest, opts ...grpc.CallOption) (*OfferCatalogReply, error)
	// 站点品牌引用批量拉取。调用方实例身份从连接凭据解析，请求体不携带身份。
	ListSiteBranding(ctx context.Context, in *ListSiteBrandingRequest, opts ...grpc.CallOption) (*ListSiteBrandingReply, error)
}

type runtimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeServiceClient(cc grpc.ClientConnInterface) RuntimeServiceClient {
	return &runtimeServiceClient{cc}
}

func (c *runtimeServiceClient) ExchangeRuntimeToken(ctx context.Context, in *ExchangeRuntimeTokenRequest, opts ...grpc.CallOption) (*ExchangeRuntimeTokenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeRuntimeTokenReply)
	err := c.cc.Invoke(ctx, RuntimeService_ExchangeRuntimeToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ResolveRegistration(ctx context.Context, in *ResolveRegistrationRequest, opts ...grpc.CallOption) (*RegistrationIntent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationIntent)
	err := c.cc.Invoke(ctx, RuntimeService_ResolveRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ConfirmRegistration(ctx context.Context, in *ConfirmRegistrationRequest, opts ...grpc.CallOption) (*RegistrationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationReply)
	err := c.cc.Invoke(ctx, RuntimeService_ConfirmRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderReply)
	err := c.cc.Invoke(ctx, RuntimeService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) VerifyAndConfirmPayment(ctx context.Context, in *VerifyAndConfirmPaymentRequest, opts ...grpc.CallOption) (*VerifyAndConfirmPaymentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAndConfirmPaymentReply)
	err := c.cc.Invoke(ctx, RuntimeService_VerifyAndConfirmPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderReply)
	err := c.cc.Invoke(ctx, RuntimeService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) SyncIdentity(ctx context.Context, in *SyncIdentityRequest, opts ...grpc.CallOption) (*IdentityReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityReply)
	err := c.cc.Invoke(ctx, RuntimeService_SyncIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) SyncVerificationStatus(ctx context.Context, in *SyncVerificationStatusRequest, opts ...grpc.CallOption) (*IdentityReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityReply)
	err := c.cc.Invoke(ctx, RuntimeService_SyncVerificationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) DisableIdentity(ctx context.Context, in *DisableIdentityRequest, opts ...grpc.CallOption) (*IdentityReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityReply)
	err := c.cc.Invoke(ctx, RuntimeService_DisableIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*BalanceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceReply)
	err := c.cc.Invoke(ctx, RuntimeService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ListLedger(ctx context.Context, in *ListLedgerRequest, opts ...grpc.CallOption) (*LedgerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedgerReply)
	err := c.cc.Invoke(ctx, RuntimeService_ListLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) GetSkuCatalog(ctx context.Context, in *GetSkuCatalogRequest, opts ...grpc.CallOption) (*SkuCatalogReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkuCatalogReply)
	err := c.cc.Invoke(ctx, RuntimeService_GetSkuCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) GetOfferCatalog(ctx context.Context, in *GetOfferCatalogRequest, opts ...grpc.CallOption) (*OfferCatalogReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfferCatalogReply)
	err := c.cc.Invoke(ctx, RuntimeService_GetOfferCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ListSiteBranding(ctx context.Context, in *ListSiteBrandingRequest, opts ...grpc.CallOption) (*ListSiteBrandingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSiteBrandingReply)
	err := c.cc.Invoke(ctx, RuntimeService_ListSiteBranding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeServiceServer is the server API for RuntimeService service.
// All implementations must embed UnimplementedRuntimeServiceServer
// for forward compatibility.
//
// RuntimeService 是工作台可调用的运行时订单与支付控制面白名单。
type RuntimeServiceServer interface {
	// ExchangeRuntimeToken 用 mTLS 客户端证书换取短期不透明访问令牌。
	ExchangeRuntimeToken(context.Context, *ExchangeRuntimeTokenRequest) (*ExchangeRuntimeTokenReply, error)
	// ResolveRegistration 解析公有 site token 或 dedicated scope，产出十分钟 intent。
	ResolveRegistration(context.Context, *ResolveRegistrationRequest) (*RegistrationIntent, error)
	// ConfirmRegistration 单事务创建身份、成员关系、归属、邀请码占用与可选赠送。
	ConfirmRegistration(context.Context, *ConfirmRegistrationRequest) (*RegistrationReply, error)
	// CreateOrder 从目录价格行冻结应付金额与当前付款方。
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderReply, error)
	// VerifyAndConfirmPayment 复验渠道原始证明并原子提交单次 grant 或周期计划。
	VerifyAndConfirmPayment(context.Context, *VerifyAndConfirmPaymentRequest) (*VerifyAndConfirmPaymentReply, error)
	// GetOrder 返回当前 actor 付款方范围内的订单稳定事实。
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderReply, error)
	// SyncIdentity 把已存在 identity 的最新生命周期事实同步为 active。
	SyncIdentity(context.Context, *SyncIdentityRequest) (*IdentityReply, error)
	// SyncVerificationStatus 只同步实名状态、时点与不可逆凭证引用。
	SyncVerificationStatus(context.Context, *SyncVerificationStatusRequest) (*IdentityReply, error)
	// DisableIdentity 把已存在 identity 的最新生命周期事实同步为 disabled。
	DisableIdentity(context.Context, *DisableIdentityRequest) (*IdentityReply, error)
	// GetBalance 按 lot 聚合派生账户账面余额与免费 / 付费拆分。
	GetBalance(context.Context, *GetBalanceRequest) (*BalanceReply, error)
	// ListLedger 按稳定全序返回用户可见额度流水。
	ListLedger(context.Context, *ListLedgerRequest) (*LedgerReply, error)
	// GetSkuCatalog 返回当前生效的公开 SKU 售价目录。
	GetSkuCatalog(context.Context, *GetSkuCatalogRequest) (*SkuCatalogReply, error)
	// GetOfferCatalog 返回当前生效的公开 Offer 售价目录。
	GetOfferCatalog(context.Context, *GetOfferCatalogRequest) (*OfferCatalogReply, error)
	// 站点品牌引用批量拉取。调用方实例身份从连接凭据解析，请求体不携带身份。
	ListSiteBranding(context.Context, *ListSiteBrandingRequest) (*ListSiteBrandingReply, error)
	mustEmbedUnimplementedRuntimeServiceServer()
}

// UnimplementedRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServiceServer struct{}

func (UnimplementedRuntimeServiceServer) ExchangeRuntimeToken(context.Context, *ExchangeRuntimeTokenRequest) (*ExchangeRuntimeTokenReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeRuntimeToken not implemented")
}
func (UnimplementedRuntimeServiceServer) ResolveRegistration(context.Context, *ResolveRegistrationRequest) (*RegistrationIntent, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveRegistration not implemented")
}
func (UnimplementedRuntimeServiceServer) ConfirmRegistration(context.Context, *ConfirmRegistrationRequest) (*RegistrationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmRegistration not implemented")
}
func (UnimplementedRuntimeServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedRuntimeServiceServer) VerifyAndConfirmPayment(context.Context, *VerifyAndConfirmPaymentRequest) (*VerifyAndConfirmPaymentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAndConfirmPayment not implemented")
}
func (UnimplementedRuntimeServiceServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedRuntimeServiceServer) SyncIdentity(context.Context, *SyncIdentityRequest) (*IdentityReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncIdentity not implemented")
}
func (UnimplementedRuntimeServiceServer) SyncVerificationStatus(context.Context, *SyncVerificationStatusRequest) (*IdentityReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncVerificationStatus not implemented")
}
func (UnimplementedRuntimeServiceServer) DisableIdentity(context.Context, *DisableIdentityRequest) (*IdentityReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableIdentity not implemented")
}
func (UnimplementedRuntimeServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*BalanceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedRuntimeServiceServer) ListLedger(context.Context, *ListLedgerRequest) (*LedgerReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLedger not implemented")
}
func (UnimplementedRuntimeServiceServer) GetSkuCatalog(context.Context, *GetSkuCatalogRequest) (*SkuCatalogReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkuCatalog not implemented")
}
func (UnimplementedRuntimeServiceServer) GetOfferCatalog(context.Context, *GetOfferCatalogRequest) (*OfferCatalogReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOfferCatalog not implemented")
}
func (UnimplementedRuntimeServiceServer) ListSiteBranding(context.Context, *ListSiteBrandingRequest) (*ListSiteBrandingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSiteBranding not implemented")
}
func (UnimplementedRuntimeServiceServer) mustEmbedUnimplementedRuntimeServiceServer() {}
func (UnimplementedRuntimeServiceServer) testEmbeddedByValue()                        {}

// UnsafeRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServiceServer will
// result in compilation errors.
type UnsafeRuntimeServiceServer interface {
	mustEmbedUnimplementedRuntimeServiceServer()
}

func RegisterRuntimeServiceServer(s grpc.ServiceRegistrar, srv RuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeService_ServiceDesc, srv)
}

func _RuntimeService_ExchangeRuntimeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeRuntimeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ExchangeRuntimeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ExchangeRuntimeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ExchangeRuntimeToken(ctx, req.(*ExchangeRuntimeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ResolveRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ResolveRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ResolveRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ResolveRegistration(ctx, req.(*ResolveRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ConfirmRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ConfirmRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ConfirmRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ConfirmRegistration(ctx, req.(*ConfirmRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_VerifyAndConfirmPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAndConfirmPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).VerifyAndConfirmPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_VerifyAndConfirmPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).VerifyAndConfirmPayment(ctx, req.(*VerifyAndConfirmPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_SyncIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).SyncIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_SyncIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).SyncIdentity(ctx, req.(*SyncIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_SyncVerificationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncVerificationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).SyncVerificationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_SyncVerificationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).SyncVerificationStatus(ctx, req.(*SyncVerificationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_DisableIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).DisableIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_DisableIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).DisableIdentity(ctx, req.(*DisableIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ListLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ListLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ListLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ListLedger(ctx, req.(*ListLedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_GetSkuCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkuCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).GetSkuCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_GetSkuCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).GetSkuCatalog(ctx, req.(*GetSkuCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_GetOfferCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOfferCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).GetOfferCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_GetOfferCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).GetOfferCatalog(ctx, req.(*GetOfferCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ListSiteBranding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSiteBrandingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ListSiteBranding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ListSiteBranding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ListSiteBranding(ctx, req.(*ListSiteBrandingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeService_ServiceDesc is the grpc.ServiceDesc for RuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.v1.RuntimeService",
	HandlerType: (*RuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExchangeRuntimeToken",
			Handler:    _RuntimeService_ExchangeRuntimeToken_Handler,
		},
		{
			MethodName: "ResolveRegistration",
			Handler:    _RuntimeService_ResolveRegistration_Handler,
		},
		{
			MethodName: "ConfirmRegistration",
			Handler:    _RuntimeService_ConfirmRegistration_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _RuntimeService_CreateOrder_Handler,
		},
		{
			MethodName: "VerifyAndConfirmPayment",
			Handler:    _RuntimeService_VerifyAndConfirmPayment_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _RuntimeService_GetOrder_Handler,
		},
		{
			MethodName: "SyncIdentity",
			Handler:    _RuntimeService_SyncIdentity_Handler,
		},
		{
			MethodName: "SyncVerificationStatus",
			Handler:    _RuntimeService_SyncVerificationStatus_Handler,
		},
		{
			MethodName: "DisableIdentity",
			Handler:    _RuntimeService_DisableIdentity_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _RuntimeService_GetBalance_Handler,
		},
		{
			MethodName: "ListLedger",
			Handler:    _RuntimeService_ListLedger_Handler,
		},
		{
			MethodName: "GetSkuCatalog",
			Handler:    _RuntimeService_GetSkuCatalog_Handler,
		},
		{
			MethodName: "GetOfferCatalog",
			Handler:    _RuntimeService_GetOfferCatalog_Handler,
		},
		{
			MethodName: "ListSiteBranding",
			Handler:    _RuntimeService_ListSiteBranding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtime.proto",
}
